# Generated by Django 2.2.2 on 2019-06-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ead/images', verbose_name='Imagem'),
        ),
    ]
