# Generated by Django 2.2.2 on 2019-06-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0002_auto_20190624_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ead',
            name='about',
            field=models.TextField(blank=True, verbose_name='Sobre o curso'),
        ),
        migrations.AlterField(
            model_name='ead',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição simples'),
        ),
    ]
